#!/usr/bin/env python
import os
import sys

from synthesizer import clone_dataset, generate_pages
from util import get_system_fonts, get_arg_switches

def main():
    switches = {"font-size": 64, "words": True, "lines": True, "num-pages": 2,
                "const-width": 0, "distort-bboxes": False, "clone-dataset": "",
                "out-dir": "./out", "load-last-seed": False, "list-fonts": False}
    switches, help_str = get_arg_switches(switches, argv=None)

    if switches["list-fonts"]:
        fontnames = get_system_fonts()
        print("\n".join(fontnames))
        print("\nTotal fonts available: {}".format(len(fontnames)))
        return

    if switches["clone-dataset"]:
        clone_dataset(switches["font-size"], switches["words"], switches["lines"], switches["out-dir"],
                      switches["load-last-seed"], switches["const-width"], switches["distort-bboxes"],
                      switches["clone-dataset"])
    else:
        generate_pages(switches["font-size"], switches["words"], switches["lines"], switches["out-dir"],
                       switches["load-last-seed"], switches["const-width"], switches["distort-bboxes"],
                       switches["num-pages"])

if __name__ == "__main__":
    main()

